export const CLASSES = [
    "Battlebro",
    "Bowslinger",
    "Hippy",
    "Knight of Tushuze",
    "Minstrel",
    "Mixologist",
    "Ne'erdowell",
    "Ragesmasher",
    "Runegoon",
    "Verbpriest",
    "Wizcaster",
    "Zoomaster"
];

export const CLASS_SKILLS = {
    "Battlebro": ["Brute Force", "Rad Moves"],
    "Bowslinger": ["Creepin'", "Spottin'"],
    "Hippy": ["Cardio", "Man vs. Wild"],
    "Knight of Tushuze": ["Believe in Yourself", "Brute Force"],
    "Minstrel": ["Believe in Yourself", "Creepin'"],
    "Mixologist": ["Macgyver", "Thinkiness"],
    "Ne'erdowell": ["Creepin'", "Macgyver"],
    "Ragesmasher": ["Brute Force", "Man vs. Wild"],
    "Runegoon": ["Cardio", "Macgyver"],
    "Verbpriest": ["Believe in Yourself", "Rad Moves"],
    "Wizcaster": ["Spottin'", "Thinkiness"],
    "Zoomaster": ["Man vs. Wild", "Rad Moves"]
};

export const CLASS_COLORS = {
    "Battlebro": "darkorange",
    "Bowslinger": "darkolivegreen",
    "Hippy": "forestgreen",
    "Knight of Tushuze": "palegoldenrod",
    "Minstrel": "royalblue",
    "Mixologist": "lightcoral",
    "Ne'erdowell": "slategray",
    "Ragesmasher": "darkred",
    "Runegoon": "cadetblue",
    "Verbpriest": "darkgoldenrod",
    "Wizcaster": "darkmagenta",
    "Zoomaster": "darkgreen"
}

export const ALTRACES = [
    //Make dynamic
    "Animal-person",
    //
    "Dwarf",
    "Edgy demon",
    "Elf (christmas)",
    "Elf (pretty)",
    "Facechanger",
    "Golem",
    "Merman",
    "Ogre",
    "Ork",
    "Thiefling",
    "Zombie"
];

export const SKILLS = [
    "Believe in Yourself",
    "Brute Force",
    "Cardio",
    "Creepin'",
    "Macgyver",
    "Man vs. Wild",
    "Rad Moves",
    "Spottin'",
    "Thinkiness"
];

export const BACKGROUNDS = [
    "Accountant",
    "Bandit",
    "Blacksmith",
    "Bureaucrat",
    "Carnie",
    "Carpenter",
    "Cheesemonger",
    "Cleric",
    "Cult member",
    "Dirt farmer",
    "Ditch digger",
    "Explorer",
    "Fisherman",
    "Gambler",
    "Goatherd",
    "Hermit",
    "Hobo",
    "Jeweler",
    "Lawyer",
    "Mercenary",
    "Messenger",
    "Miner",
    "Musician",
    "Pirate(yarr)",
    "Professional athlete",
    "Scammer",
    "Schoolteacher",
    "Servant",
    "Shoemaker",
    "Soldier",
    "Stablehand",
    "Tailor",
    "Thief",
    "Trust fund baby",
    "Waiter",
    "Wizard’s apprentice"
]

export const ELEMENTS = [
    "Acid",
    "Bee",
    "Bone",
    "Chaos",
    "Crystal",
    "Darkness",
    "Earth",
    "Fear",
    "Flame",
    "Force",
    "Glass",
    "Gold",
    "Goop",
    "Ice",
    "Laser",
    "Life",
    "Light",
    "Lightning",
    "Madness",
    "Magma",
    "Meme",
    "Metal",
    "Mind",
    "Plant",
    "Poison",
    "Rat",
    "Sleep",
    "Smoke",
    "Sound",
    "Sparkle",
    "Stasis",
    "Stink",
    "Time",
    "Water",
    "Weather",
    "Wind"
];

export const ELEMENTS_OF = [
    "Acid",
    "Bees",
    "Bones",
    "Chaos",
    "Crystal",
    "Darkness",
    "Earth",
    "Fear",
    "Flame",
    "Force",
    "Glass",
    "Gold",
    "Goop",
    "Ice",
    "Laser",
    "Life",
    "Light",
    "Lightning",
    "Madness",
    "Magma",
    "Memes",
    "Metal",
    "Mind",
    "Plants",
    "Poison",
    "Rats",
    "Sleep",
    "Smoke",
    "Sound",
    "Sparkles",
    "Stasis",
    "Stink",
    "Time",
    "Water",
    "Weather",
    "Wind"
];

export const VERBS = [
    "Absorb",
    "Blast",
    "Blind",
    "Charm",
    "Conceal",
    "Control",
    "Crush",
    "Curse",
    "Deceive",
    "Destroy",
    "Duplicate",
    "Enlarge",
    "Ensnare",
    "Explode",
    "Hasten",
    "Heal",
    "Hinder",
    "Immobilize",
    "Levitate",
    "Nullify",
    "Pierce",
    "Protect",
    "Regenerate",
    "Repel",
    "Restore",
    "Reveal",
    "See",
    "Shrink",
    "Silence",
    "Summon",
    "Teleport",
    "Terrify",
    "Transform",
    "Understand",
    "Warp",
    "Wither"
];

export const GERUNDS = [
    "Absorbing",
    "Blasting",
    "Blinding",
    "Charming",
    "Concealing",
    "Controling",
    "Crushing",
    "Cursing",
    "Deceiving",
    "Destroying",
    "Duplicating",
    "Enlarging",
    "Ensnaring",
    "Exploding",
    "Hastening",
    "Healing",
    "Hindering",
    "Immobilizing",
    "Levitating",
    "Nullifying",
    "Piercing",
    "Protecting",
    "Regenerating",
    "Repeling",
    "Restoring",
    "Revealing",
    "Seeing",
    "Shrinking",
    "Silencing",
    "Summoning",
    "Teleporting",
    "Terrifying",
    "Transforming",
    "Understanding",
    "Warping",
    "Withering"
];

export const FORMS = [
    "Armor",
    "Arrow",
    "Aura",
    "Ball",
    "Beam",
    "Blade",
    "Blast",
    "Bubble",
    "Burst",
    "Circle",
    "Cloak",
    "Cloud",
    "Cube",
    "Dance",
    "Disk",
    "Field",
    "Gaze",
    "Golem",
    "Line",
    "Pants",
    "Portal",
    "Pulse",
    "Ray",
    "Servant",
    "Shield",
    "Song",
    "Steed",
    "Storm",
    "Swarm",
    "Touch",
    "Trap",
    "Vortex",
    "Wall",
    "Wave",
    "Wings",
    "Word"
]

//index 0-17 == Melee
//index 18-35 == Ranged
export const WEAPONS = [
    "Battleaxe",
    "Beatstick",
    "Broadsword",
    "Claymore",
    "Dagger",
    "Flail",
    "Gauntlets",
    "Hatchet",
    "Knife",
    "Mace",
    "Polearm",
    "Rapier",
    "Scimitar",
    "Scythe",
    "Short sword",
    "Spear",
    "Staff",
    "Whip",
    "Arbalest",
    "Blunderbuss",
    "Bolas",
    "Boomerang",
    "Chakram",
    "Composite bow",
    "Crossbow",
    "Heavy rock",
    "Hunting bow",
    "Javelins",
    "Longbow",
    "Musket",
    "Pistol",
    "Recurve bow",
    "Shuriken",
    "Sling",
    "Throwing axes",
    "Throwing knives"
];

export const TRINKETS = [
    "Amulet",
    "Bells",
    "Book",
    "Boots",
    "Bottle",
    "Cloak",
    "Clock",
    "Codpiece",
    "Coin",
    "Contraption",
    "Device",
    "Gloves",
    "Goggles",
    "Hat",
    "Helmet",
    "Holy Symbol",
    "Incense",
    "Jewel",
    "Mask",
    "Monocle",
    "Necklace",
    "Orb",
    "Paint",
    "Pants",
    "Pen",
    "Ring",
    "Robe",
    "Rod",
    "Shirt",
    "Skull",
    "Staff",
    "Statuette",
    "Talisman",
    "Totem",
    "Wand",
    "Wig"
]

export const EQUIPMENT = [
    `${random(BACKGROUNDS)} tools`,
    `Bear Trap`,
    `Bomb`,
    `Caltrops`,
    `Chain(10 ft.)`,
    `Crowbar`,
    `Disguise Kit`,
    `Food(1 day)`,
    `Flask of oil`,
    `Glue`,
    `Grappling hook`,
    `Hammer and chisel`,
    `Horn`,
    `Hourglass`,
    `Ladder`,
    `Lantern`,
    `Lockpicks`,
    `Long stick`,
    `Manacles`,
    `Medicine`,
    `${random(WEAPONS.slice(0,18))}`,
    `Mirror`,
    `Musical instrument`,
    `Net`,
    `Plot device(consume to regain 1 Plot Point)`,
    `${random(WEAPONS.slice(19,36))}`,
    `Rope(50 ft.)`,
    `Sack`,
    `Shield`,
    `Shovel`,
    `Spyglass`,
    `Torch`,
    `${random(TRINKETS)}`,
    `Tripwire`,
    `Vial of acid`,
    `Vial of poison`
];

export const AERIAL_CREATURES = [
    "Albatross",
    "Condor",
    "Eagle",
    "Falcon",
    "Flamingo",
    "Flying Squirrel",
    "Fruit Bat",
    "Hawk",
    "Hummingbird",
    "Owl",
    "Parrot",
    "Pelican",
    "Pigeon",
    "Pterodactyl",
    "Seagull",
    "Sparrow",
    "Vampire Bat",
    "Vulture",
]

export const AQUATIC_CREATURES = [
    "Algae Eater",
    "Angler Fish",
    "Crab",
    "Crocodile",
    "Dolphin",
    "Electric Eel",
    "Frog",
    "Grouper",
    "Hippopotamus",
    "Jellyfish",
    "Lamprey",
    "Lionfish",
    "Lobster",
    "Manatee",
    "Moray Eel",
    "Muskrat",
    "Narwhal",
    "Nautilus",
    "Octopus",
    "Penguin",
    "Platypus",
    "Plesiosaur",
    "Pufferfish",
    "Salmon",
    "Sea Sponge",
    "Sea Urchin",
    "Seahorse",
    "Sealion",
    "Shark",
    "Shrimp",
    "Squid",
    "Starfish",
    "Stingray",
    "Swordfish",
    "Turtle",
    "Whale",
]

export const BUG_CREATURES = [
    "Army Ant",
    "Bee",
    "Bombardier Beetle",
    "Butterfly",
    "Caterpillar",
    "Centipede",
    "Cockroach",
    "Daddy-Long-Legs",
    "Dragonfly",
    "Dungbeetle",
    "Earthworm",
    "Fire Ant",
    "Firefly",
    "Flea",
    "Fly",
    "Grasshopper",
    "Grub",
    "Ladybug",
    "Mantis",
    "Millipede",
    "Mosquito",
    "Moth",
    "Pillbug",
    "Rhinoceros Beetle",
    "Scarab",
    "Scorpion",
    "Silverfish",
    "Slug",
    "Snail",
    "Spider",
    "Tarantula",
    "Termite",
    "Tick",
    "Trapdoor Spider",
    "Wasp",
    "Weevil",
]

export const PREDATOR_CREATURES = [
    "Ape",
    "Baboon",
    "Cheetah",
    "Fox",
    "Grizzly Bear",
    "Hyena",
    "Jackal",
    "Jaguar",
    "Komodo Dragon",
    "Lion",
    "Polar Bear",
    "Python",
    "T-Rex",
    "Tiger",
    "Velociraptor",
    "Viper",
    "Weasel",
    "Wolf",
]

export const PREY_CREATURES = [
    "Bison",
    "Boar",
    "Deer",
    "Diplodocus",
    "Gazelle",
    "Giraffe",
    "Lizard",
    "Mole",
    "Monkey",
    "Ostrich",
    "Porcupine",
    "Rabbit",
    "Rat",
    "Rhinoceros",
    "Skunk",
    "Stegosaurus",
    "Tapir",
    "Triceratops",
]

export const DOMESTICATED_CREATURES = [
    "Camel",
    "Cat",
    "Chicken",
    "Cow",
    "Dog(Big)",
    "Dog(Small)",
    "Duck",
    "Goat",
    "Hedgehog",
    "Horse",
    "Hound",
    "Llama",
    "Ox",
    "Pig",
    "Raccoon",
    "Sheep",
    "Squirrel",
    "Turkey",
]

export const MUTATIONS = [
    `${random(AERIAL_CREATURES)} feature`,
    `${random(AQUATIC_CREATURES)} feature`,
    `${random(BUG_CREATURES)} feature`,
    `${random(PREDATOR_CREATURES)} feature`,
    `${random(PREY_CREATURES)} feature`,
    `${random(DOMESTICATED_CREATURES)} feature`,
    `${random(AERIAL_CREATURES)} feature`,
    `${random(AQUATIC_CREATURES)} feature`,
    `${random(BUG_CREATURES)} feature`,
    `${random(PREDATOR_CREATURES)} feature`,
    `${random(PREY_CREATURES)} feature`,
    `${random(DOMESTICATED_CREATURES)} feature`,
    `Adorable`,
    `Armor plating`,
    `Deafening shriek`,
    `${random(ELEMENTS)} body`,
    `${random(ELEMENTS)} breath`,
    `Extra eyes`,
    `Extra limbs`,
    `Gelatinous`,
    `Ghostly`,
    `Giant mouth`,
    `Huge`,
    `Humanoid form`,
    `Hypnosis`,
    `Invisibility`,
    `Life drain`,
    `Nightmarish`,
    `Plantimal`,
    `Regeneration`,
    `Self-duplication`,
    `Shapeshifting`,
    `Stench`,
    `Stretchy`,
    `Teleportation`,
    `Two-headed`
]

export const SONGS = [
    "Aria",
    "Dirge",
    "Groove",
    "Hoedown",
    "Limerick",
    "Lullaby",
    "Jingle",
    "March",
    "Power Ballad",
    "Rap",
    "Shanty",
    "Solo"
]

export const BASES = [
    "Bomb",
    "Brew",
    "Decoction",
    "Elixir",
    "Emulsion",
    "Grenade",
    "Infusion",
    "Oil",
    "Poison",
    "Potion",
    "Powder",
    "Resin"
]

export function random(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

export function randomAnimal() {
    return random(random([AERIAL_CREATURES, AQUATIC_CREATURES, BUG_CREATURES, PREDATOR_CREATURES, PREY_CREATURES, DOMESTICATED_CREATURES]));
}

export function randomMagicItem() {
    return random([
        `${random(ELEMENTS)} ${random(EQUIPMENT)}`,
        `${random(ELEMENTS)} ${random(TRINKETS)}`,
        `${random(GERUNDS)} ${random(EQUIPMENT)}`,
        `${random(GERUNDS)} ${random(TRINKETS)}`,
        `${random(EQUIPMENT)} of ${random(GERUNDS)}`,
        `${random(TRINKETS)} of ${random(GERUNDS)}`,
        `${random(GERUNDS)} ${random(WEAPONS)}`,
        `${random(ELEMENTS)} ${random(WEAPONS)}`,
        `${random(TRINKETS)} of ${random(GERUNDS)} ${random(ELEMENTS_OF)}`,
        `${random(WEAPONS)} of ${random(GERUNDS)} ${random(ELEMENTS_OF)}`,
        `${random(GERUNDS)} Potion`,
        `Potion of ${random(ELEMENTS_OF)}`
    ])
}