export const CLASSES = [
    "Battlebro",
    "Bowslinger",
    "Hippy",
    "Knight of Tushuze",
    "Minstrel",
    "Mixologist",
    "Ne'erdowell",
    "Ragesmasher",
    "Runegoon",
    "Verbpriest",
    "Wizcaster",
    "Zoomaster"
];

export const CLASS_SKILLS = {
    "Battlebro": ["Brute Force", "Rad Moves"],
    "Bowslinger": ["Creepin'", "Spottin'"],
    "Hippy": ["Cardio", "Man vs. Wild"],
    "Knight of Tushuze": ["Believe in Yourself", "Brute Force"],
    "Minstrel": ["Believe in Yourself", "Creepin'"],
    "Mixologist": ["Macgyver", "Thinkiness"],
    "Ne'erdowell": ["Creepin'", "Macgyver"],
    "Ragesmasher": ["Brute Force", "Man vs. Wild"],
    "Runegoon": ["Cardio", "Macgyver"],
    "Verbpriest": ["Believe in Yourself", "Rad Moves"],
    "Wizcaster": ["Spottin'", "Thinkiness"],
    "Zoomaster": ["Man vs. Wild", "Rad Moves"]
};

export const CLASS_COLORS = {
    "Battlebro": "darkorange",
    "Bowslinger": "darkolivegreen",
    "Hippy": "forestgreen",
    "Knight of Tushuze": "palegoldenrod",
    "Minstrel": "royalblue",
    "Mixologist": "lightcoral",
    "Ne'erdowell": "slategray",
    "Ragesmasher": "darkred",
    "Runegoon": "cadetblue",
    "Verbpriest": "darkgoldenrod",
    "Wizcaster": "darkmagenta",
    "Zoomaster": "darkgreen"
}

export const SKILLS = [
    "Believe in Yourself",
    "Brute Force",
    "Cardio",
    "Creepin'",
    "Macgyver",
    "Man vs. Wild",
    "Rad Moves",
    "Spottin'",
    "Thinkiness"
];

export const SKILL_USES = {
    "Believe in Yourself": "Charming, leading, willpower, dumb luck",
    "Brute Force": "Punching, lifting, breaking stuff, being scary",
    "Cardio": "Running, swimming, climbing, stamina, healthiness",
    "Creepin'": "Sneaking, stealing, lying, general skullduggery",
    "Macgyver": "Crafting, building, forging, making stuff",
    "Man vs. Wild": "Surviving, foraging, riding, animal handling, nature knowledge",
    "Rad Moves": "Dodging, running, jumping, acrobatics, balance",
    "Spottin'": "Shooting, looking, noticing, awareness, precision",
    "Thinkiness": "Knowing, remembering, wits, historical, scientific, and arcane knowledge"
}

export const BACKGROUNDS = [
    "Accountant",
    "Bandit",
    "Blacksmith",
    "Bureaucrat",
    "Carnie",
    "Carpenter",
    "Cheesemonger",
    "Cleric",
    "Cult member",
    "Dirt farmer",
    "Ditch digger",
    "Explorer",
    "Fisherman",
    "Gambler",
    "Goatherd",
    "Hermit",
    "Hobo",
    "Jeweler",
    "Lawyer",
    "Mercenary",
    "Messenger",
    "Miner",
    "Musician",
    "Pirate(yarr)",
    "Professional athlete",
    "Scammer",
    "Schoolteacher",
    "Servant",
    "Shoemaker",
    "Soldier",
    "Stablehand",
    "Tailor",
    "Thief",
    "Trust fund baby",
    "Waiter",
    "Wizard’s apprentice"
]

export const APPEARANCES = [
    "Androgynous",
    "Angry",
    "Ascetic",
    "Athletic",
    "Bedraggled",
    "Boney",
    "Bookish",
    "Bro",
    "Creepy",
    "Dirty",
    "Edgelord",
    "Fancy",
    "Formal",
    "Hairy",
    "Hipster",
    "Immaculate",
    "Jacked",
    "Like someone famous",
    "Mustachioed",
    "Mystical",
    "Nervous",
    "Perfect hair",
    "Punk",
    "Rad",
    "Scarred",
    "Sharp - dressed",
    "Skeezy",
    "Spacey",
    "Straight - laced",
    "Tattooed",
    "Theatrical",
    "Trendy",
    "Unremarkable",
    "Weary",
    "Weird",
    "Wild"
]

export const DERPS = [
    "Allergic to a color",
    "Allergic to common substance",
    "Anger management issues",
    "Annoying habit",
    "Arms like twizzlers",
    "Boyscout",
    "Bro",
    "Complete idiot",
    "Compulsive snacker",
    "Debbie downer",
    "Deficient personal hygiene",
    "Delusions of grandeur",
    "Doesn’t believe in money",
    "Dogmatic libertarian",
    "Emotionless",
    "Fantasy racism (vs. humans)",
    "Fantasy racism (vs. non-humans)",
    "Formerly wealthy",
    "Functionally illiterate",
    "Has to pet animals",
    "High-functioning alcoholic",
    "Hipster",
    "Hypochondriac",
    "In a cult",
    "Incredibly boring",
    "Invents junk",
    "Just a total asshole",
    "Light of innocence",
    "Lumbering oaf",
    "Makes stuff up",
    "Memelord",
    "Modern anachronism",
    "Naked avarice",
    "Narcissist",
    "Narcolepsy",
    "Neurotic",
    "Only speaks Gronk",
    "On probation",
    "Paranoia",
    "Pathological liar",
    "Poor short term memory",
    "Pronoia(they’re all out to help me!)",
    "Pseudo intellectual",
    "Pyromania",
    "Quixotic quest",
    "Raised by Animals",
    "Religious zealot",
    "Rolls dice before doing anything",
    "Says 'yes' to everything",
    "Severe IBS",
    "Shit luck",
    "Short attention span",
    "Slacker",
    "Sovereign Citizen",
    "Stone-age luddite",
    "Talks to rocks",
    "Tells stories that go nowhere",
    "Thinks they're a vampire",
    "Thinks they are/aren’t a wizard",
    "Thinks they’re a superhero",
    "Thinks they’re in an rpg",
    "Thinks they’re psychic",
    "*Tips fedora* M’lady",
    "Tinfoil hat",
    "Too old for this shit",
    "Trapped in a long con",
    "Unhelpful imaginary friend",
    "Unsuccessful casanova",
    "Wannabe bard",
    "Wanted",
    "Washed up celebrity",
    "Yellow-bellied coward"
]

export const ELEMENTS = [
    "Acid",
    "Bee",
    "Bone",
    "Chaos",
    "Crystal",
    "Darkness",
    "Earth",
    "Fear",
    "Flame",
    "Force",
    "Glass",
    "Gold",
    "Goop",
    "Ice",
    "Laser",
    "Life",
    "Light",
    "Lightning",
    "Madness",
    "Magma",
    "Meme",
    "Metal",
    "Mind",
    "Plant",
    "Poison",
    "Rat",
    "Sleep",
    "Smoke",
    "Sound",
    "Sparkle",
    "Stasis",
    "Stink",
    "Time",
    "Water",
    "Weather",
    "Wind"
];

export const ELEMENTS_OF = [
    "Acid",
    "Bees",
    "Bones",
    "Chaos",
    "Crystal",
    "Darkness",
    "Earth",
    "Fear",
    "Flame",
    "Force",
    "Glass",
    "Gold",
    "Goop",
    "Ice",
    "Lasers",
    "Life",
    "Light",
    "Lightning",
    "Madness",
    "Magma",
    "Memes",
    "Metal",
    "Mind",
    "Plants",
    "Poison",
    "Rats",
    "Sleep",
    "Smoke",
    "Sound",
    "Sparkles",
    "Stasis",
    "Stink",
    "Time",
    "Water",
    "Weather",
    "Wind"
];

export const VERBS = [
    "Absorb",
    "Blast",
    "Blind",
    "Charm",
    "Conceal",
    "Control",
    "Crush",
    "Curse",
    "Deceive",
    "Destroy",
    "Duplicate",
    "Enlarge",
    "Ensnare",
    "Explode",
    "Hasten",
    "Heal",
    "Hinder",
    "Immobilize",
    "Levitate",
    "Nullify",
    "Pierce",
    "Protect",
    "Regenerate",
    "Repel",
    "Restore",
    "Reveal",
    "See",
    "Shrink",
    "Silence",
    "Summon",
    "Teleport",
    "Terrify",
    "Transform",
    "Understand",
    "Warp",
    "Wither"
];

export const GERUNDS = [
    "Absorbing",
    "Blasting",
    "Blinding",
    "Charming",
    "Concealing",
    "Controlling",
    "Crushing",
    "Cursing",
    "Deceiving",
    "Destroying",
    "Duplicating",
    "Enlarging",
    "Ensnaring",
    "Exploding",
    "Hastening",
    "Healing",
    "Hindering",
    "Immobilizing",
    "Levitating",
    "Nullifying",
    "Piercing",
    "Protecting",
    "Regenerating",
    "Repeling",
    "Restoring",
    "Revealing",
    "Seeing",
    "Shrinking",
    "Silencing",
    "Summoning",
    "Teleporting",
    "Terrifying",
    "Transforming",
    "Understanding",
    "Warping",
    "Withering"
];

export const FORMS = [
    "Armor",
    "Arrow",
    "Aura",
    "Ball",
    "Beam",
    "Blade",
    "Blast",
    "Bubble",
    "Burst",
    "Circle",
    "Cloak",
    "Cloud",
    "Cube",
    "Dance",
    "Disk",
    "Field",
    "Gaze",
    "Golem",
    "Line",
    "Pants",
    "Portal",
    "Pulse",
    "Ray",
    "Servant",
    "Shield",
    "Song",
    "Steed",
    "Storm",
    "Swarm",
    "Touch",
    "Trap",
    "Vortex",
    "Wall",
    "Wave",
    "Wings",
    "Word"
]

//index 0-17 == Melee
//index 18-35 == Ranged
export const WEAPONS = [
    "Battleaxe",
    "Beatstick",
    "Broadsword",
    "Claymore",
    "Dagger",
    "Flail",
    "Gauntlets",
    "Hatchet",
    "Knife",
    "Mace",
    "Polearm",
    "Rapier",
    "Scimitar",
    "Scythe",
    "Short sword",
    "Spear",
    "Staff",
    "Whip",
    "Arbalest",
    "Blunderbuss",
    "Bolas",
    "Boomerang",
    "Chakram",
    "Composite bow",
    "Crossbow",
    "Heavy rock",
    "Hunting bow",
    "Javelins",
    "Longbow",
    "Musket",
    "Pistol",
    "Recurve bow",
    "Shuriken",
    "Sling",
    "Throwing axes",
    "Throwing knives"
];

export const TRINKETS = [
    "Amulet",
    "Bells",
    "Book",
    "Boots",
    "Bottle",
    "Cloak",
    "Clock",
    "Codpiece",
    "Coin",
    "Contraption",
    "Device",
    "Gloves",
    "Goggles",
    "Hat",
    "Helmet",
    "Holy Symbol",
    "Incense",
    "Jewel",
    "Mask",
    "Monocle",
    "Necklace",
    "Orb",
    "Paint",
    "Pants",
    "Pen",
    "Ring",
    "Robe",
    "Rod",
    "Shirt",
    "Skull",
    "Staff",
    "Statuette",
    "Talisman",
    "Totem",
    "Wand",
    "Wig"
]

export const EQUIPMENT = [
    `${random(BACKGROUNDS)} tools`,
    `Bear trap`,
    `Bomb`,
    `Caltrops`,
    `Chain (10 ft.)`,
    `Crowbar`,
    `Disguise kit`,
    `Food (1 day)`,
    `Flask of oil`,
    `Glue`,
    `Grappling hook`,
    `Hammer and chisel`,
    `Horn`,
    `Hourglass`,
    `Ladder`,
    `Lantern`,
    `Lockpicks`,
    `Long stick`,
    `Manacles`,
    `Medicine`,
    `${random(WEAPONS.slice(0,18))}`,
    `Mirror`,
    `Musical instrument`,
    `Net`,
    `Spare ammo`,
    `${random(WEAPONS.slice(19,36))}`,
    `Rope (50 ft.)`,
    `Sack`,
    `Shield`,
    `Shovel`,
    `Spyglass`,
    `Torch`,
    `${random(TRINKETS)}`,
    `Tripwire`,
    `Vial of acid`,
    `Vial of poison`
];

export const AERIAL_CREATURES = [
    "Albatross",
    "Condor",
    "Eagle",
    "Falcon",
    "Flamingo",
    "Flying Squirrel",
    "Fruit Bat",
    "Hawk",
    "Hummingbird",
    "Owl",
    "Parrot",
    "Pelican",
    "Pigeon",
    "Pterodactyl",
    "Seagull",
    "Sparrow",
    "Vampire Bat",
    "Vulture",
]

export const AQUATIC_CREATURES = [
    "Algae Eater",
    "Angler Fish",
    "Crab",
    "Crocodile",
    "Dolphin",
    "Electric Eel",
    "Frog",
    "Grouper",
    "Hippopotamus",
    "Jellyfish",
    "Lamprey",
    "Lionfish",
    "Lobster",
    "Manatee",
    "Moray Eel",
    "Muskrat",
    "Narwhal",
    "Nautilus",
    "Octopus",
    "Penguin",
    "Platypus",
    "Plesiosaur",
    "Pufferfish",
    "Salmon",
    "Sea Sponge",
    "Sea Urchin",
    "Seahorse",
    "Sealion",
    "Shark",
    "Shrimp",
    "Squid",
    "Starfish",
    "Stingray",
    "Swordfish",
    "Turtle",
    "Whale",
]

export const BUG_CREATURES = [
    "Army Ant",
    "Bee",
    "Bombardier Beetle",
    "Butterfly",
    "Caterpillar",
    "Centipede",
    "Cockroach",
    "Daddy-Long-Legs",
    "Dragonfly",
    "Dungbeetle",
    "Earthworm",
    "Fire Ant",
    "Firefly",
    "Flea",
    "Fly",
    "Grasshopper",
    "Grub",
    "Ladybug",
    "Mantis",
    "Millipede",
    "Mosquito",
    "Moth",
    "Pillbug",
    "Rhinoceros Beetle",
    "Scarab",
    "Scorpion",
    "Silverfish",
    "Slug",
    "Snail",
    "Spider",
    "Tarantula",
    "Termite",
    "Tick",
    "Trapdoor Spider",
    "Wasp",
    "Weevil",
]

export const PREDATOR_CREATURES = [
    "Ape",
    "Baboon",
    "Cheetah",
    "Fox",
    "Grizzly Bear",
    "Hyena",
    "Jackal",
    "Jaguar",
    "Komodo Dragon",
    "Lion",
    "Polar Bear",
    "Python",
    "T-Rex",
    "Tiger",
    "Velociraptor",
    "Viper",
    "Weasel",
    "Wolf",
]

export const PREY_CREATURES = [
    "Bison",
    "Boar",
    "Deer",
    "Diplodocus",
    "Gazelle",
    "Giraffe",
    "Lizard",
    "Mole",
    "Monkey",
    "Ostrich",
    "Porcupine",
    "Rabbit",
    "Rat",
    "Rhinoceros",
    "Skunk",
    "Stegosaurus",
    "Tapir",
    "Triceratops",
]

export const DOMESTICATED_CREATURES = [
    "Camel",
    "Cat",
    "Chicken",
    "Cow",
    "Dog(Big)",
    "Dog(Small)",
    "Duck",
    "Goat",
    "Hedgehog",
    "Horse",
    "Hound",
    "Llama",
    "Ox",
    "Pig",
    "Raccoon",
    "Sheep",
    "Squirrel",
    "Turkey",
]

export const ALTRACES = [
    `${randomAnimal()}-person`,
    "Dwarf",
    "Edgy demon",
    "Elf (christmas)",
    "Elf (pretty)",
    "Facechanger",
    "Golem",
    "Merman",
    "Ogre",
    "Ork",
    "Thiefling",
    "Zombie"
];

export const MUTATIONS = [
    `${random(AERIAL_CREATURES)} feature`,
    `${random(AQUATIC_CREATURES)} feature`,
    `${random(BUG_CREATURES)} feature`,
    `${random(PREDATOR_CREATURES)} feature`,
    `${random(PREY_CREATURES)} feature`,
    `${random(DOMESTICATED_CREATURES)} feature`,
    `${random(AERIAL_CREATURES)} feature`,
    `${random(AQUATIC_CREATURES)} feature`,
    `${random(BUG_CREATURES)} feature`,
    `${random(PREDATOR_CREATURES)} feature`,
    `${random(PREY_CREATURES)} feature`,
    `${random(DOMESTICATED_CREATURES)} feature`,
    `Adorable`,
    `Armor plating`,
    `Deafening shriek`,
    `${random(ELEMENTS)} body`,
    `${random(ELEMENTS)} breath`,
    `Extra eyes`,
    `Extra limbs`,
    `Gelatinous`,
    `Ghostly`,
    `Giant mouth`,
    `Huge`,
    `Humanoid form`,
    `Hypnosis`,
    `Invisibility`,
    `Life drain`,
    `Nightmarish`,
    `Plantimal`,
    `Regeneration`,
    `Self-duplication`,
    `Shapeshifting`,
    `Stench`,
    `Stretchy`,
    `Teleportation`,
    `Two-headed`
]

export const SONGS = [
    random(["Aria", "Ballad"]),
    random(["Groove", "Hoedown"]),
    random(["Jig", "Shanty"]),
    random(["Dirge", "Lullaby"]),
    random(["Power Chord", "Solo"]),
    random(["Limerick", "Rap Battle"])
]

export const BASES = [
    "Bomb",
    "Brew",
    "Decoction",
    "Elixir",
    "Emulsion",
    "Grenade",
    "Infusion",
    "Oil",
    "Poison",
    "Potion",
    "Powder",
    "Resin"
]

export const RUNES = [
    'ᚠ','ᚡ','ᚢ','ᚣ','ᚤ','ᚥ','ᚦ','ᚧ','ᚨ','ᚩ','ᚪ','ᚫ','ᚬ','ᚭ','ᚮ','ᚯ','ᚰ','ᚱ',
    'ᚲ','ᚳ','ᚴ','ᚵ','ᚶ','ᚷ','ᚸ','ᚹ','ᚺ','ᚻ','ᚼ','ᚽ','ᚾ','ᚿ','ᛀ','ᛁ','ᛂ','ᛃ',
    'ᛄ','ᛅ','ᛇ','ᛈ','ᛉ','ᛊ','ᛋ','ᛒ','ᛓ','ᛔ','ᛕ','ᛖ','ᛗ','ᛘ','ᛝ','ᛞ','ᛟ','ᛠ','ᛢ','ᛤ','ᛥ','ᛩ','ᛪ'
]

export const COMMANDS = [
    "Attack",
    "Begone",
    "Burn",
    "Collapse",
    "Cooperate",
    "Cower",
    "Dance",
    "Defend",
    "Disappear",
    "Flail",
    "Float",
    "Fly",
    "Follow",
    "Forget",
    "Freeze",
    "Give",
    "Grow",
    "Help",
    "Move",
    "Open",
    "Pose",
    "Protect",
    "Run",
    "Scream",
    "Shake",
    "Shoot",
    "Shrink",
    "Silence",
    "Sing",
    "Sleep",
    "Speak",
    "Stop",
    "Surrender",
    "Take",
    "Throw",
    "Wallop"
]

export const RESOURCE_ITEMS = [
    "Weapon Oil",
    "Animal Totem",
    "Scroll of Power",
    "Command Scroll",
    "Songbook",
    "Holy Symbol",
    "Alchemical Ingredient"
]

export const STARTING_ITEMS = {
    //And add standard items: 8 - package.length
    //Feed into switch statement, default: selected string
    "Battlebro": [
        ["Graduate Weapon"], ["Ranged Weapon", "Shield"], ["Potion of Healing", "Weapon Oil"]
    ],
    "Bowslinger": [
        ["Ranged Weapon"], ["Melee Weapon", "Spare ammo"], ["Net", "Bear trap"], ["Potion of Healing", "Weapon Oil"]
    ],
    "Hippy": [
        ["Melee Weapon", "Ranged Weapon"], ["Medicinal Herb", "Vial of poison"], ["Animal Totem", "Magic Item"]
    ],
    "Knight of Tushuze": [
        ["Melee Weapon"], ["Ranged Weapon", "Shield"], ["Potion of Healing", "Magic Item"]
    ],
    "Minstrel": [
        ["Melee Weapon", "Ranged Weapon"], ["Musical instrument", "Horn"], ["Lockpicks", "Disguise Kit"], ["Songbook", "Magic Item"]
    ],
    "Mixologist": [
        ["Melee Weapon", "Ranged Weapon"], ["Alchemist's tools"], ["Vial of acid", "Vial of poison"], ["Potion of Healing", "2 Alchemical Ingredients"]
    ],
    "Ne'erdowell": [
        ["Melee Weapon", "Ranged Weapon"], ["Lockpicks", "Grappling hook"], ["Caltrops", "Crowbar"], ["Magic Item"]
    ],
    "Ragesmasher": [
        ["Melee Weapon"], ["Melee Weapon", "Ranged Weapon"], ["Potion of Healing", "Animal Totem"],
    ],
    "Runegoon": [
        ["Melee Weapon", "Ranged Weapon"], ["Paint"], ["Blacksmith's tools", "Mason's tools"], ["Scroll of Power", "Magic Item"]
    ],
    "Verbpriest": [
        ["Melee Weapon", "Ranged Weapon"], ["Cleric's tools", "Horn"], ["Potion of Healing", "Scroll of Power"]
    ],
    "Wizcaster": [
        ["Staff", "Dagger"], ["Ranged Weapon", "Bookbinder's tools"], ["Scroll of Power", "Magic Item"]
    ],
    "Zoomaster": [
        ["Melee Weapon", "Ranged Weapon"], ["Shield", "Spare ammo"], ["Potion of Healing", "Animal Totem"]
    ]
}

export function random(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

export function randomRace() {
    if (Math.floor(Math.random() * 100) <= 66) {
        return "Human";
    } else {
        return random(ALTRACES);
    }
}

export function randomAnimal() {
    return random(random([AERIAL_CREATURES, AQUATIC_CREATURES, BUG_CREATURES, PREDATOR_CREATURES, PREY_CREATURES, DOMESTICATED_CREATURES]));
}

export function randomMagicItem() {
    return random([
        `${random(ELEMENTS)} ${random(EQUIPMENT)}`,
        `${random(ELEMENTS)} ${random(TRINKETS)}`,
        `${random(GERUNDS)} ${random(EQUIPMENT)}`,
        `${random(GERUNDS)} ${random(TRINKETS)}`,
        `${random(EQUIPMENT)} of ${random(GERUNDS)}`,
        `${random(TRINKETS)} of ${random(GERUNDS)}`,
        `${random(GERUNDS)} ${random(WEAPONS)}`,
        `${random(ELEMENTS)} ${random(WEAPONS)}`,
        `${random(TRINKETS)} of ${random(GERUNDS)} ${random(ELEMENTS_OF)}`,
        `${random(WEAPONS)} of ${random(GERUNDS)} ${random(ELEMENTS_OF)}`,
        `${random(GERUNDS)} ${random(BASES)}`,
        `${random(BASES)} of ${random(ELEMENTS_OF)}`
    ])
}

export function randomResourceItem(resource) {
    switch (resource) {
        case "Weapon Oil":
            return `Weapon Oil of ${random([random(ELEMENTS_OF), random(GERUNDS)])}`;
        case "Animal Totem":
            return `${randomAnimal()} with ${random(MUTATIONS)} Totem`
        case "Scroll of Power":
            return `Scroll of ${random([random(GERUNDS), random(ELEMENTS)])}`
        case "Command Scroll":
            return `Scroll of ${random(COMMANDS)}`
        case "Songbook":
            return `Songbook of ${random([random(ELEMENTS_OF), random(GERUNDS)])}`
        case "Holy Symbol":
            return `Holy Symbol of ${random(SKILLS)}`
        case "Alchemical Ingredient":
            return `${random([random(BASES) + " Base", random(ELEMENTS_OF) + " Catalyst", random(GERUNDS)])}`
        default:
            return randomResourceItem(random(RESOURCE_ITEMS))
    }
}